spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace  # SQL ? ? ? ?? ? ??? ? ???